# Generated by Django 2.1.1 on 2018-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('stuid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('tele', models.CharField(max_length=250)),
                ('class1', models.CharField(max_length=250)),
                ('major', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
