# Generated by Django 2.1.1 on 2018-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='stuid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
