# Generated by Django 2.1.1 on 2018-12-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0003_auto_20181203_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='tele',
        ),
        migrations.AddField(
            model_name='product',
            name='gold',
            field=models.CharField(db_index=True, default='True', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tel',
            field=models.CharField(db_index=True, default='True', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='sells.User'),
        ),
    ]
