# Generated by Django 2.1.1 on 2018-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0006_auto_20181210_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/2018/12/publishphotos'),
        ),
    ]
