# Generated by Django 2.1.1 on 2018-12-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0007_auto_20181219_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
    ]
