# Generated by Django 2.1.1 on 2018-12-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sell_stuid',
        ),
    ]
